#!/usr/bin/env ruby
# Trace route53 and Load Balancers related to the given domain
require 'aws-sdk-route53'
require 'aws-sdk-elasticloadbalancing'
require 'aws-sdk-elasticloadbalancingv2'
require 'aws-sdk-ec2'
require 'optparse'

def list_hosted_zones(client)
  hosted_zones = []
  marker = nil
  loop do
    resp = client.list_hosted_zones({
      marker: marker,
    })
    hosted_zones.concat resp.hosted_zones
    break unless resp.is_truncated
    marker = resp.next_marker
  end
  # p hosted_zones.map(&:name)
  hosted_zones
end

def list_resource_record_sets(client, hosted_zone)
  records = []
  start_record_name = nil
  start_record_type = nil
  start_record_identifier = nil
  loop do
    resp = client.list_resource_record_sets({
      start_record_name: start_record_name,
      start_record_type: start_record_type,
      start_record_identifier: start_record_identifier,
      hosted_zone_id: hosted_zone.id
    })
    records.concat resp.resource_record_sets
    break unless resp.is_truncated
    start_record_name = resp.next_record_name
    start_record_type = resp.next_record_type
    start_record_identifier = resp.next_record_identifier
  end
  # p records
  # p records.map(&:name)
  records
end

def describe_load_balancers(client)
  marker = nil
  load_balancers = []
  loop do
    resp = client.describe_load_balancers({
      marker: marker,
    })
    load_balancers.concat resp.load_balancer_descriptions
    marker = resp.next_marker
    break unless marker
  end
  load_balancers
end

def describe_load_balancersv2(client)
  marker = nil
  load_balancers = []
  loop do
    resp = client.describe_load_balancers({
      marker: marker,
    })
    load_balancers.concat resp.load_balancers
    marker = resp.next_marker
    break unless marker
  end
  load_balancers
end

def describe_listeners(client, load_balancer)
  marker = nil
  listeners = []
  loop do
    resp = client.describe_listeners({
      load_balancer_arn: load_balancer.load_balancer_arn,
      marker: marker,
    })
    listeners.concat resp.listeners
    marker = resp.next_marker
    break unless marker
  end
  listeners
end

def describe_rules(client, listener)
  marker = nil
  rules = []
  loop do
    resp = client.describe_rules({
      listener_arn: listener.listener_arn,
      marker: marker,
    })
    rules.concat resp.rules
    marker = resp.next_marker
    break unless marker
  end
  rules
end

def describe_target_groups(client, target_group_arns)
  marker = nil
  target_groups = []
  loop do
    resp = client.describe_target_groups({
      target_group_arns: target_group_arns,
      marker: marker,
    })
    target_groups.concat resp.target_groups
    marker = resp.next_marker
    break unless marker
  end
  target_groups
end

def describe_instances(client, instance_ids)
  marker = nil
  instances = []
  loop do
    resp = client.describe_instances({
      instance_ids: instance_ids,
      next_token: marker,
    })
    resp.reservations.each do |reservation|
      instances.concat reservation.instances
    end
    marker = resp.next_token
    break unless marker
  end
  instances
end

def describe_security_groups(client, group_ids)
  marker = nil
  security_groups = []
  loop do
    resp = client.describe_security_groups({
      group_ids: group_ids,
      next_token: marker,
    })
    security_groups.concat resp.security_groups
    marker = resp.next_token
    break unless marker
  end
  security_groups
end

def describe_target_health(client, target_group_arn)
  resp = client.describe_target_health({
    target_group_arn: target_group_arn,
  })
  resp.target_health_descriptions
end

def main
  opt = OptionParser.new("usage: traceroute53 <domain>")

  profile = ENV['AWS_PROFILE']
  opt.on('--profile PROFILE', "use given profile") {|v| profile = v }

  opt.parse!(ARGV)
  domain = ARGV.shift
  unless domain
    puts opt.help
    exit
  end

  client = Aws::Route53::Client.new(
    region: 'us-east-1',
    profile: profile,
  )

  hosted_zones = list_hosted_zones(client)
  domain_dot = domain + '.'
  zones = hosted_zones.select{|zone| domain_dot.end_with?(zone.name)}
  if zones.empty?
    STDERR.puts "hosted zone not found for #{domain}"
    exit 1
  end
  # p zones
  hosted_zone = zones.sort_by{|zone| zone.name.size}.last
  # p hosted_zone
  puts "hosted zone: #{hosted_zone.name}"

  record_sets = list_resource_record_sets(client, hosted_zone)
  while true
    records = record_sets.select{|r| r.name == domain_dot}
    if records.empty?
      STDERR.puts "resource record set not found in #{hosted_zone} for #{domain}"
      exit 1
    end
    if records.size != 1
      STDERR.puts records.inspect
      STDERR.puts "more than one resource record set in #{hosted_zone} for #{domain}"
      exit 1
    end
    record = records[0]
    if record.alias_target
      # The record is an AWS resource
      dns_name = record.alias_target.dns_name
      puts "dns name: #{dns_name}"
      # https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Route53/Types/AliasTarget.html
      if /\.elb\.(?:[a-z0-9\-]+\.)?amazonaws.com\.\z/ =~ dns_name
        break
      elsif /\.amazonaws.com\.\z/ =~ dns_name
        STDERR.puts record.inspect
        STDERR.puts "unsupported AWS resource '#{dns_name}'; pull request is welcome https://github.com/nurse/traceroute53"
      exit 1
      else
        # assune Another Route 53 resource record set
        domain_dot = dns_name
      end
    elsif record.type == 'CNAME'
      puts "resource_records: #{record.resource_records.map(&:value)}"
      domain_dot = record.resource_records[0].value
    else
      STDERR.puts record.inspect
      STDERR.puts "unsupported record; pull request is welcome https://github.com/nurse/traceroute53"
      exit 1
    end
  end
  dns_name.sub!(/\Adualstack\./, '')
  dns_name.chomp!('.')

  unless /([a-z0-9\-]+)?\.elb\.(?:([a-z0-9\-]+)\.)?amazonaws.com\z/ =~ dns_name
    STDERR.puts "dns_name:#{dns_name} doesn't include AWS region name"
    exit 1
  end
  region = $2 || $1

  instance_ids = nil
  begin
    # Aws::ElasticLoadBalancingV2 (Application Load Balancer or Network Load Balancer)
    client = Aws::ElasticLoadBalancingV2::Client.new(
      region: region,
      profile: profile,
    )
    load_balancers = describe_load_balancersv2(client)
    # it raises LoadBalancerNotFound exception if not found
    load_balancer = load_balancers.find{|lb| lb.dns_name == dns_name}
    puts "load balancer: #{load_balancer.load_balancer_name} #{load_balancer.security_groups}"

    listeners = describe_listeners(client, load_balancer)
    if listeners.empty?
      STDERR.puts "listeners not found in #{region} for #{load_balancer}"
      exit 1
    end

    instance_ids = []
    target_group_arns = {}
    listeners.each_with_index do |listener, i|
      # p listener
      puts "listener[#{i}]: port:#{listener.port} #{listener.listener_arn}"
      rules = describe_rules(client, listener)
      rules.each_with_index do |rule, j|
        puts "listener[#{i}]rule[#{j}]: #{rule.rule_arn}#{rule.is_default ? ' (default)' : ''}"
        rule.conditions.each_with_index do |condition, k|
          puts "listener[#{i}]rule[#{j}]condition[#{k}]: #{condition.values}"
        end
        rule.actions.each_with_index do |action, k|
          puts "listener[#{i}]rule[#{j}]action[#{k}]: #{action.type} #{action.target_group_arn}"
          if target_group_arns[action.target_group_arn]
            puts "listener[#{i}]rule[#{j}]action[#{k}]: the target group is already showed; skip"
          else
            target_group_arns[action.target_group_arn] = true
            target_healths = describe_target_health(client, action.target_group_arn)
            target_healths.each_with_index do |health, l|
              puts "listener[#{i}]rule[#{j}]action[#{k}]target[#{l}]: #{health.target.id}:#{health.target.port} #{health.target_health.state}"
              instance_ids << health.target.id
            end
          end
        end
      end
    end
    instance_ids

    # p target_group_arns
    # target_groups = describe_target_groups(client, target_group_arns)
    # if target_groups.empty?
    #   STDERR.puts "target groups not found in #{region} for #{listeners}"
    #   exit 1
    # end
    # p target_groups

    unless instance_ids
      STDERR.puts "load balancers not found in #{region} for #{dns_name} with ELBv2"
      # exit 1
    end
  rescue Aws::ElasticLoadBalancingV2::Errors::LoadBalancerNotFound
    STDERR.puts "load balancers not found in #{region} for #{dns_name} with ELBv2"
  end

  unless instance_ids
    # Aws::ElasticLoadBalancing (Classic Load Balancer)
    client = Aws::ElasticLoadBalancing::Client.new(
      region: region,
      profile: profile,
    )
    load_balancers = describe_load_balancers(client)
    if load_balancers.empty?
      STDERR.puts "load balancers not found in #{region} for #{dns_name}"
      exit 1
    end

    load_balancer = load_balancers.find{|lb| lb.dns_name == dns_name}
    instance_ids = []
    unless load_balancer
      load_balancers.each_with_index do |lb, i|
        STDERR.puts "load balancer[#{i}]: #{lb.dns_name}"
      end
      STDERR.puts "load balancers not found in #{region} for #{dns_name}"
      exit 1
    end

    load_balancer = load_balancers[0]
    puts "load balancer: #{load_balancer.load_balancer_name} #{load_balancer.security_groups}"

    load_balancer.instances.each_with_index do |instance, i|
      puts "instances[#{i}]: #{instance[:instance_id]}"
      instance_ids << instance[:instance_id]
    end
  end

  # Inspect Security Group
  client = Aws::EC2::Client.new(
    region: region,
    profile: profile,
  )
  instances = describe_instances(client, instance_ids)
  group_ids_hash = {}
  instances.each do |instance|
    group_ids = instance.security_groups.map(&:group_id)
    group_ids_hash[group_ids] ||= []
    group_ids_hash[group_ids] << instance.instance_id
  end

  # Assume that instances under an ELB have the same security groups.
  # If they are varied, something weird is happening and it needs further investigation...
  group_ids_hash.each_pair.with_index do |(group_ids, instance_ids), i|
    puts "group_ids[#{i}]: #{group_ids}"
    puts "group_ids[#{i}]: #{instance_ids}"
    security_groups = describe_security_groups(client, group_ids)
    security_groups.each_with_index do |sg, j|
      puts "group_ids[#{i}]sg[#{j}]: #{sg.group_id}"
      sg.ip_permissions.each_with_index do |ip, k|
        puts "group_ids[#{i}]sg[#{j}]ip[#{k}]: port:#{ip.from_port.inspect} #{ip.user_id_group_pairs.map(&:group_id)}"
      end
    end
  end
end
main
